apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi  # Ensure this label matches the ServiceMonitor selector
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - name: http  # Port name used in ServiceMonitor
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
